### ISSUE TITLE
Where do you save the digital twins?

### ISSUE THREAD

**Issue by Yushi-Du** [UT-Austin-RPL/Ditto#10]
Hi! I'm new to the way your code organizes and I wonder where the output of the model is. And how to visualize it using the utils3d tools?
Many thanks!

**Comment by Steve-Tod** [comment]
Hi! Do you mean the output during training/validation? If you just want to test our model, you can refer to the [demo](https://github.com/UT-Austin-RPL/Ditto/blob/master/notebooks/demo_depth_map.ipynb) notebook. It contains the whole pipeline for running and visualization.

**Comment by Yushi-Du** [comment]
Sorry for replying so late and appreciate your help a lot! I've solved the problem and run into another one. What do 'screw_axis' and 'screw_moment' stand for in your dataset? I'm a little confused about that reading the code. I'm truly grateful for your help!

**Comment by Steve-Tod** [comment]
Hi, `screw_axis` is the direction vector of the joint axis, and `screw_moment` is the cross product between a point on the axis and the axis direction. You can refer to the Background section of [ScrewNet](https://arxiv.org/abs/2008.10518):
<img width="420" alt="image" src="https://user-images.githubusercontent.com/26958167/191556380-12e1d2d8-6c91-4e77-b7ef-fb5a2d0998c7.png">

**Comment by Yushi-Du** [comment]
Thank you very much!! I'll read the doc carefully!
