### ISSUE TITLE
Different visualization result in demo_depth_map.ipynb

### ISSUE THREAD

**Issue by RobinWangSD** [UT-Austin-RPL/Ditto#2]
I have been replicating the visualization result shown in demo_depth_map.ipynb (https://github.com/UT-Austin-RPL/Ditto/blob/master/notebooks/demo_depth_map.ipynb). The following are the steps I executed:
1. Clone the Ditto repo and create a virtual env in PyCharm. (Python 3.8.10). Then perform the rest in the created virtual env.
2. install the required packages by 'pip install -r requirements.txt'
3. build the dependencies by 'python scripts/convonet_setup.py build_ext --inplace'
4. collect all the required data and put them under root/data directory, following the README.m (https://github.com/UT-Austin-RPL/Ditto#data-and-pre-trained-models, https://utexas.box.com/s/ujb2ky8y9vaog7nheth1n3tmm1rgx9t7, https://utexas.box.com/s/a4h001b3ciicrt3f71t4xd3wjsm04be7, https://utexas.box.com/s/zbf5bja20n2w6umryb1bcfbbcm3h2ysn)
5. install an older version of utils3d by 'pip install git+git://github.com/Steve-Tod/utils3d.git@bbd72687404436b37c90230a572891075aa8a53b' because the Pyrenderer in the newest located at a different path and will cause error when executing in my env.
6. Then I directly run all the cells in demo_depth_map.ipynb, and get the following results (from different viewpoints)

![output1](https://user-images.githubusercontent.com/91654517/157773839-01e1add5-5614-4d46-b235-035f1d7f637b.png)
![output2](https://user-images.githubusercontent.com/91654517/157773840-512485c3-497d-4a79-bb2a-7fad1666b4c2.png)

The prismatic joint axis looks different from the demo and meshes of both digital twins from my result seem to be incomplete.

Below are the pic from demo.
![download](https://user-images.githubusercontent.com/91654517/157774062-5ceb3c9e-72bc-47a3-89b0-9279f9084a6d.png)

**Comment by Steve-Tod** [comment]
Hi, I just found out we used a different model weight to get the real-world results. It's trained for a longer time. It does not give a very good quantitative result, but it seems to generalize better to real-world scenarios without the need to tunning the marching cube parameters. The model is [here](https://utexas.box.com/s/ktckf75xo33plf5nidyvqz9bn20jwv06). I'll also update it in the README.

**Comment by 123zhen123** [comment]
> Hi, I just found out we used a different model weight to get the real-world results. It's trained for a longer time. It does not give a very good quantitative result, but it seems to generalize better to real-world scenarios without the need to tunning the marching cube parameters. The model is [here](https://utexas.box.com/s/ktckf75xo33plf5nidyvqz9bn20jwv06). I'll also update it in the README.

Thank you very much for your answer. I have the same problem. But this [link](https://utexas.box.com/s/ktckf75xo33plf5nidyvqz9bn20jwv06) seems to have been defunct, could you please send it again?

Meanwhile, I used "real_laptop.zip" data in "demo_depth_map.ipynb", but in IN [7] , I got incomplete point cloud. This looks different from the results provided. Is there some discrepancy in the data?
<img width="553" alt="image" src="https://user-images.githubusercontent.com/38036089/170234078-9ab7b9eb-1f43-41f7-bf19-925935b4da78.png">
