### ISSUE TITLE
How to visualize the test results of shape2motion dataset?

### ISSUE THREAD

**Issue by buptmjj** [UT-Austin-RPL/Ditto#3]
Hi, according to the tutorial, I have realized the visualization of test results of the real word dataset, which depends on the input of depth images and RGB images. However, how to visualize the test results of the shape2motion dataset? Thank you very much for your help!

**Comment by Steve-Tod** [comment]
Hi, visualizing test results would be even easier. You just need to create a datamodule from the config file by running `datamodule = hydra.utils.instantiate(config.datamodule)`, and get dataloader by `dl = datamodule.test_dataloader()`. Then you can roll out the data and pass them into the network as shown in the demo, and visualize the results using the same code.

**Comment by buptmjj** [comment]
> 

Thank you very much for your help. You are so excellent! But can you show me what you modified? I don't know where to modify the code.

**Comment by Steve-Tod** [comment]
Hi, you can use this code to instantiate the datamodule with config:
```Python
datamodule = hydra.utils.instantiate(config.datamodule)
datamodule.setup()
dl = datamodule.test_dataloader()
it = iter(dl)
```
And this code to rollout the data:
```Python
sample = next(it)
for k, v in sample.items():
    if isinstance(v, torch.Tensor):
        sample[k] = v.to(device)
```

**Comment by buptmjj** [comment]
> Hi, you can use this code to instantiate the datamodule with config:
> 
> ```python
> datamodule = hydra.utils.instantiate(config.datamodule)
> datamodule.setup()
> dl = datamodule.test_dataloader()
> it = iter(dl)
> ```
> 
> And this code to rollout the data:
> 
> ```python
> sample = next(it)
> for k, v in sample.items():
>     if isinstance(v, torch.Tensor):
>         sample[k] = v.to(device)
> ```

Thank you very much. With your help, I have completed this task!
