### ISSUE TITLE
What are the data contained in the camera2base.json file?

### ISSUE THREAD

**Issue by buptmengjj** [UT-Austin-RPL/Ditto#4]
Hi, I'd like to ask what data are contained in camera2base.json file? It looks like the pose of the camera, but what does the base coordinate system mean?

**Comment by Steve-Tod** [comment]
It contains the camera poses of all the images. The coordinate system follows the one in `open3d`.

**Comment by buptmengjj** [comment]
> 它包含所有图像的相机姿势。坐标系遵循 中的坐标系`open3d`。

Thank you very much!
