### ISSUE TITLE
Can you share the process of data pre-processing?

### ISSUE THREAD

**Issue by buptmengjj** [UT-Austin-RPL/Ditto#5]
Hi, Can you share the process of data pre-processing? We think your work can bring some inspiration to our research. Thank you very much!

**Comment by Steve-Tod** [comment]
Those codes are quite messy now. If you need them, I'll release the code for data generation once I get a chance to clean it up.

**Comment by buptmengjj** [comment]
> Those codes are quite messy now. If you need them, I'll release the code for data generation once I get a chance to clean it up.

Yes, I need. I would be very grateful if you could release them!

**Comment by Steve-Tod** [comment]
I see, I'll work on it when I have time.

**Comment by buptmengjj** [comment]
Hello, we want to make a dataset and input it into your network for experiment. Before you publish the data pre-processing process, I learned about the content of shape2motion dataset. In the process, I have some problems and hope to get your help. Firstly, I use np.shape() outputs the dimension of data ["start_occ_list"], and the result is (n, 100000). I think n represents the number of parts of the object, but what does the data 1000000 represent? Secondly, what is the content of data[start_p_occ]? Thank you very much for your help!

**Comment by Steve-Tod** [comment]
That's the number of occupancy point samples. "start_p_occ" is the query points for occupancy at the start frame (before interaction). "start_occ_list" is the corresponding list of occupancy results for each part.

**Comment by buptmengjj** [comment]
Hi！ I really appreciate your patience in answering my questions. I learned from the paper—— "the ground_truth occupancy is queried from the ground truth mesh", but  I'm wondering how did you get the ground truth mesh of the object before and after the interaction?

**Comment by Steve-Tod** [comment]
Hi, we get ground truth through API in `Pybullet`, like [here](https://github.com/UT-Austin-RPL/GIGA/blob/d67c4388d334babe6c11c1555a6e848fb4828c84/src/vgn/utils/implicit.py#L33).

**Comment by buptmengjj** [comment]
Hi, are the pc_seg_start and pc_seg_end  also queried from mesh? Can you share the code about segmentation? In addition, how to get the screw_axis and the screw_moment? Thank you very much, you really helped me a lot!

**Comment by Steve-Tod** [comment]
Hi there, I finished cleaning up the data generation code and released it [here](https://github.com/UT-Austin-RPL/Ditto_data_gen). You can refer to the code here for more details.

pc_seg_start and pc_seg_end were not used in Ditto. screw_axis and screw_moment are from Pybullet.

**Comment by buptmengjj** [comment]
> Hi there, I finished cleaning up the data generation code and released it [here](https://github.com/UT-Austin-RPL/Ditto_data_gen). You can refer to the code here for more details.
> 
> pc_seg_start and pc_seg_end were not used in Ditto. screw_axis and screw_moment are from Pybullet.

Your release is very timely. Thank you very much!
