### ISSUE TITLE
What's the meaning of 'recenter' when inferencing the pivot point

### ISSUE THREAD

**Issue by Jianghanxiao** [UT-Austin-RPL/Ditto#8]
Hi,

Thanks for your great work. When going through the demo code, I don't quite understand about the recenter process. Can you help exaplain a bit. Based on my current understanding, the pivot point has been the averaged motion origin. Why do we want another recenter operation? What's the use of the double cross?

`if recenter:
        pivot_point = np.cross(axis, np.cross(pivot_point, axis))`

**Comment by Jianghanxiao** [comment]
Ohhh, it's the point on the axis here. It can be proved like this as long as the axis is normalized (length = 1)

![Image from iOS](https://user-images.githubusercontent.com/32015651/178408810-04d1d545-9e25-461b-a09e-d0dfc4d11e1f.jpg)

**Comment by Steve-Tod** [comment]
Yeah, it's mainly for visualization purposes, I want to make sure the axis center is close to the origin so that visualized axis is visible.
